// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGWvE00MptC7S3fKOHU4gPlPu6EsGKv-8',
    appId: '1:355716240276:web:3f30122a670b82d3c7f581',
    messagingSenderId: '355716240276',
    projectId: 'todosync-r16m07',
    authDomain: 'todosync-r16m07.firebaseapp.com',
    databaseURL: 'https://todosync-r16m07-default-rtdb.firebaseio.com',
    storageBucket: 'todosync-r16m07.appspot.com',
    measurementId: 'G-6PX9RTTXD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy0Eolj5Jb5xx7smPS_UB3EUZjyvVq5x4',
    appId: '1:355716240276:android:115bc7c57b382462c7f581',
    messagingSenderId: '355716240276',
    projectId: 'todosync-r16m07',
    databaseURL: 'https://todosync-r16m07-default-rtdb.firebaseio.com',
    storageBucket: 'todosync-r16m07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiv7B_cEt1c3BlrIxBlACbN_r1Uo94nto',
    appId: '1:355716240276:ios:8364f49893036654c7f581',
    messagingSenderId: '355716240276',
    projectId: 'todosync-r16m07',
    databaseURL: 'https://todosync-r16m07-default-rtdb.firebaseio.com',
    storageBucket: 'todosync-r16m07.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiv7B_cEt1c3BlrIxBlACbN_r1Uo94nto',
    appId: '1:355716240276:ios:8364f49893036654c7f581',
    messagingSenderId: '355716240276',
    projectId: 'todosync-r16m07',
    databaseURL: 'https://todosync-r16m07-default-rtdb.firebaseio.com',
    storageBucket: 'todosync-r16m07.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );
}
